In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,0,0],[0,0.5,0],[0,0,0.25]])

In [3]:
matrix

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

In [16]:
vector = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
vector

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
vector_t = np.transpose(vector)

In [25]:
vector_post = np.matmul(matrix,vector)
vector_post

array([[1.  , 2.  , 3.  ],
       [2.  , 2.5 , 3.  ],
       [1.75, 2.  , 2.25]])

In [26]:
vector_post_t = np.matmul(matrix,vector_t)
vector_post_t

array([[1.  , 4.  , 7.  ],
       [1.  , 2.5 , 4.  ],
       [0.75, 1.5 , 2.25]])

In [28]:
np.transpose(vector_post_t)

array([[1.  , 1.  , 0.75],
       [4.  , 2.5 , 1.5 ],
       [7.  , 4.  , 2.25]])

In [30]:
np.matmul(vector,np.transpose(matrix))

array([[1.  , 1.  , 0.75],
       [4.  , 2.5 , 1.5 ],
       [7.  , 4.  , 2.25]])